### ISSUE TITLE
Injector: filter on schedule store

### ISSUE THREAD

**Issue by geertw** [geertw/rdt-serviceinfo#19]
With the introduction of InfoPlus-PPV, many train replacing bus services are already available in the InfoPlus feed and do not need to be injected to rdt-infoplus-dvs anymore. However, bus services that are provided via ARNU still need to be injected.

This is a injector configuration used in production:

```yaml
injector:
    injector_server: tcp://127.0.0.1:8140
    window: 70
    selection:
        transport_mode:
#            - B
            - BNS
            - NSB
            - NSM
            - NSS
            - NST
```

Possibly, it should look like:

```yaml
injector:
    injector_server: tcp://127.0.0.1:8140
    window: 70
    selection:
        transport_mode:
            - store: actual
              modes:
                  - B
            - store: any
              modes:
                  - BNS
                  - NSB
                  - NSM
                  - NSS
                  - NST
```
